### ISSUE TITLE
Transparent mounting of local folder as a regular folder

### ISSUE THREAD

**Issue by cphyc** [jupyterlab-contrib/jupyterlab-filesystem-access#33]
Currently, the only files that can be accessed from a _pyodide_ kernel are those in the "internal memory" of the instance. This can be alleviated by uploading manually files, but it is cumbersome and not practical if the number of files is large.

## Describe the solution you'd like

Instead, it would be helpful to have a way of “mounting” a folder in the file system as a folder accessible to jupyterlite through the filesystem API so that the pyodide kernel has a transparent access to local files on the hard drive.

## Describe alternatives you've considered

Drag and dropping files works, but it is cumbersome and unpractical for a large number of files and requires all files to be uploaded prior to doing any work. It is also possible to rely on ipywidgets to upload files with the same limitations.

## Additional context

- Related to jupyterlite/pyodide only, this is not required for classical jupyterlab instances.

**Comment by martinRenou** [comment]
This should be resolved in JupyterLite soon, by https://github.com/jupyterlite/jupyterlite/pull/655
