### ISSUE TITLE
Extension does not work in JupyterLab v4

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab-contrib/jupyterlab-filesystem-access#54]
The extension does not seem to work in JupyterLab v4:

- the extension icon does not render in the side toolbar, and as such, the extension functionality appears not to be accessible.

**Comment by jtpio** [comment]
Thanks @psychemedia for reporting :+1: 

Likely the extension will have to be updated to JupyterLab 4.

Also it looks like there was already an issue with the toolbar before so not sure it's related to lab 4: https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access/pull/32

**Comment by psychemedia** [comment]
Yeah - I noticed that; I was demoing to folk using a pinned old JupyterLite and hadn't realised it had broken some time ago.. (Academic schedule means I only look at a lot of things once a year, June-August, in advance of September start, when things get pinned for the next academic year.)
