### ISSUE TITLE
Files created from launcher are not mapped to the remote filesystem

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab-contrib/jupyterlab-filesystem-access#65]
If I try to create a new notebook by clicking the launcher button, the new notebook does not appear in the remote filesystem directory and is not listed in the remote filesystem listing in the file browser.

If I right-click in the file browser and create a new file there, it does appear in the file listing in the sidebar and is saved to the remote filesystem.

*I also have the `jupyterlab-git` and `jupyterlab-unfold` extensions installed which interact with the filesytem and file listing display.*

*The ability for the UI to display notebooks that are saved to different file systems makes me wonder if it might be useful to identify the file system for example by colouring the background of the filename tab, or changing it's favicon?*

**Comment by martinRenou** [comment]
This should be fixed by https://github.com/jupyterlab/jupyterlab/issues/15290
